name: actions

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9.6
      uses: actions/setup-python@v4
      with:
        python-version: 3.9.6
        
    - name: Install dependencies
      run: make install

    - name: Load data
      run: make load-data

    - name: Train model
      run: make train

    - name: Test model
      run: make test

    - name: Build Docker image
      run: make docker-build
